In [ ]:
#1a*
fin=open('in.txt','r')
A=list(map(int,fin.read().split('\n')))
cnt=0
for i in range(1,len(A)):
    if A[i-1]<A[i]:
        cnt+=1
cnt

In [5]:
#1b
fin=open('in.txt','r')
A=list(map(int,fin.read().split('\n')))
cnt=0
A=[A[i-2]+A[i-1]+A[i] for i in range(2,len(A))]
for i in range(1,len(A)):
    if A[i-1]<A[i]:
        cnt+=1
cnt

1724

In [ ]:
#2a*
fin=open('in.txt','r')
h,d=0,0
for l in fin.read().split('\n'):
    pcs=l.split(' ')
    pcs[1]=int(pcs[1])
    if pcs[0]=='forward':
        h+=pcs[1]
    elif pcs[0]=='down':
        d+=pcs[1]
    else:
        d-=pcs[1]
print(h*d)

In [15]:
#2b
fin=open('in.txt','r')
h,d,a=0,0,0
for l in fin.read().split('\n'):
    pcs=l.split(' ')
    x=int(pcs[1])
    if pcs[0]=='forward':
        h+=x
        d+=a*x
    elif pcs[0]=='down':
        #d+=x
        a+=x
    else:
        #d-=x
        a-=x
print(h*d)

1599311480


In [17]:
#3a
fin=open('in.txt','r')
A=fin.read().split('\n')
print(len(A))
g,e=0,0
for c in range(len(A[0])):
    n1=0
    for r in range(len(A)):
        if A[r][c]=='1':
            n1+=1
    b=2**(len(A[0])-1-c)
    if n1>len(A)/2:
        g+=b
    else:
        e+=b
print(g*e)

1000
3901196


In [25]:
#3b
fin=open('in.txt','r')
A=fin.read().split('\n')
C=len(A[0])
co2,og=0,0
B=A[:]
for c in range(C):
    if len(B)==1:
        break
    n=[0]*2
    for r in range(len(B)):
        n[int(B[r][c])]+=1
    m=1 if n[1]>=n[0] else 0
    B=[b for b in B if int(b[c])==m]
print(B)
co2=B[0]
B=A[:]
for c in range(C):
    if len(B)==1:
        break
    n=[0]*2
    for r in range(len(B)):
        n[int(B[r][c])]+=1
    m=1 if n[1]<n[0] else 0
    B=[b for b in B if int(b[c])==m]
og=B[0]
print(int(co2,2)*int(og,2))

['011001100111']
4412188


In [ ]:
#4a*
fin=open('in.txt','r')
L=fin.read().split('\n')
A=list(map(int,L[0].split(',')))
#print(A)
N=5
def won(M):
    for row in M:
        good=True
        for b in row:
            if not(b):
                good=False
                break
        if good:
            return True
    for c in range(N):
        good=True
        for r in range(N):
            if not(M[r][c]):
                good=False
                break
        if good:
            return True
    return False
Bs=[]
i=2
while i<len(L):
    ss=L[i:i+5]
    m=[]
    for r in ss:
        m.append([int(r[j:j+3]) for j in range(0,15,3)])
    Bs.append(m)
    #Bs.append(list(map(lambda row:list(map(int,row.strip().split(' '))),L[i:i+5])))
    i+=6
#print(Bs)
B=len(Bs)
Ms=[[[False]*N for r in range(N)] for b in range(B)]
done=False
for v in A:
    for i in range(B):
        M=Ms[i]
        for r in range(N):
            for c in range(N):
                if Bs[i][r][c]==v:
                    M[r][c]=True
        if won(M):
            print(Bs[i])
            print(M)
            s=0
            for r in range(N):
                for c in range(N):
                    if not(M[r][c]):
                        s+=Bs[i][r][c]
            print(s*v)
            done=True
            break
    if done:
        break

In [381]:
#4b**
fin=open('in.txt','r')
L=fin.read().split('\n')
A=list(map(int,L[0].split(',')))
#print(A)
N=5
def won(M):
    for row in M:
        good=True
        for b in row:
            if not(b):
                good=False
                break
        if good:
            return True
    for c in range(N):
        good=True
        for r in range(N):
            if not(M[r][c]):
                good=False
                break
        if good:
            return True
    return False
Bs=[]
i=2
while i<len(L):
    ss=L[i:i+5]
    m=[]
    for r in ss:
        m.append([int(r[j:j+3]) for j in range(0,15,3)])
    Bs.append(m)
    #Bs.append(list(map(lambda row:list(map(int,row.strip().split(' '))),L[i:i+5])))
    i+=6
#print(Bs)
B=len(Bs)
Ms=[[[False]*N for r in range(N)] for b in range(B)]
done=[False]*B
for v in A:
    for i in range(B):
        if not(done[i]):
            M=Ms[i]
            for r in range(N):
                for c in range(N):
                    if Bs[i][r][c]==v:
                        M[r][c]=True
            if won(M):
                #print(Bs[i])
                #print(M)
                s=0
                for r in range(N):
                    for c in range(N):
                        if not(M[r][c]):
                            s+=Bs[i][r][c]
                print(s*v)
                done[i]=True
#             done=True
#             break
#     if done:
#         break

46920
71994
54444
59280
36114
955
29835
53004
68262
15912
25704
31038
4886
4053
4739
47320
42168
64032
50324
47520
38790
19116
20160
12168
25160
21632
29172
29380
36800
42585
27710
25925
31575
22606
61766
58918
58117
36579
34020
33138
15015
13497
13530
13002
13200
10560
1468
2188
27126
24684
29898
9129
6732
11237
8755
5933
43904
20064
26904
1062
774
891
3393
21168
21330
27162
25488
20628
0
52264
27166
44838
13108
28835
33496
35155
20313
23485
35197
22095
14040
11835
19035
23994
5520
3392
15330
46277
23870
20824
2172
2076
13110
25270
24120
15192
14061
12556
30567
12635


In [ ]:
#5a*
fin=open('in.txt','r')
L=fin.read().split('\n')
lines=[]
for l in L:
    ends=l.split(' -> ')
    lines.append(list(map(lambda e:list(map(int,e.split(','))),ends)))
freq={}
def add(p):
    freq[p]=1+(freq[p] if p in freq else 0)
for l in lines:
    x0,y0,x1,y1=l[0][0],l[0][1],l[1][0],l[1][1]
    #print(x0,y0,x1,y1)
    if x0==x1:
        for y in range(min(y0,y1),max(y0,y1)+1):
            add((x0,y))
    elif y0==y1:
        for x in range(min(x0,x1),max(x0,x1)+1):
            add((x,y0))
cnt=0
for p in freq:
    if freq[p]>1:
        cnt+=1
print(cnt)

In [61]:
#5b
fin=open('in.txt','r')
L=fin.read().split('\n')
lines=[]
for l in L:
    ends=l.split(' -> ')
    lines.append(list(map(lambda e:list(map(int,e.split(','))),ends)))
freq={}
def add(p):
    freq[p]=1+(freq[p] if p in freq else 0)
for l in lines:
    x0,y0,x1,y1=l[0][0],l[0][1],l[1][0],l[1][1]
    #print(x0,y0,x1,y1)
    if x0==x1:
        for y in range(min(y0,y1),max(y0,y1)+1):
            add((x0,y))
    elif y0==y1:
        for x in range(min(x0,x1),max(x0,x1)+1):
            add((x,y0))
    else:
        dx,dy=1 if x0<x1 else -1,1 if y0<y1 else -1
        for s in range(max(y0,y1)+1-min(y0,y1)):
            add((x0+dx*s,y0+dy*s))
cnt=0
for p in freq:
    if freq[p]>1:
        cnt+=1
print(cnt)

18423


In [64]:
#6a
fin=open('in.txt','r')
A=list(map(int,fin.read().split(',')))
D=80
for d in range(D):
    nnew=0
    for i in range(len(A)):
        if A[i]==0:
            A[i]=6
            nnew+=1
        else:
            A[i]-=1
    A=A+[8]*nnew
print(len(A))

352872


In [67]:
#6b
fin=open('in.txt','r')
A=list(map(int,fin.read().split(',')))
F=[0]*9
for v in A:
    F[v]+=1
D=256
for d in range(D):
    nF=[0]*9
    for t in range(1,9):
        nF[t-1]=F[t]
    nF[6]+=F[0]
    nF[8]+=F[0]
    F=nF
print(sum(F))

1604361182149


In [73]:
#7a
fin=open('in.txt','r')
A=list(map(int,fin.read().split(',')))
A=sorted(A)
m=A[len(A)//2]
print(sum([abs(v-m) for v in A]))

336131


In [76]:
#7b
fin=open('in.txt','r')
A=list(map(int,fin.read().split(',')))
bm,bscr=None,float('inf')
for m in range(min(A),max(A)+1):
    scr=0
    for v in A:
        n=abs(v-m)
        scr+=n*(n+1)//2
    if scr<bscr:
        bscr=scr
        bm=m
print(bscr)

92676646


In [78]:
#8a
fin=open('in.txt','r')
#masks='1110111,0010010,1011101,1011011,0111010,1101011,1101111,1010010,1111111,1111011'.split(',')
L=fin.read().split('\n')
D={2:1,4:4,3:7,7:8}
cnt=0
for l in L:
    p=l.split(' | ')[1].split(' ')
    for s in p:
        if len(s) in D:
            cnt+=1
print(cnt)

387


In [99]:
#8b
import itertools
fin=open('in.txt','r')
masks='1110111,0010010,1011101,1011011,0111010,1101011,1101111,1010010,1111111,1111011'.split(',')
masks={masks[i]:i for i in range(10)}
print(masks)
L=fin.read().split('\n')
cnt=0
def tomask(s):
    m=[0]*7
    for c in s:
        m[ord(c)-ord('a')]+=1
    return m
for l in L:
    P=tuple(map(lambda s:s.split(' '),l.split(' | ')))
    Ms=[]
    for s in P[0]:
        Ms.append(tomask(s))
    #print(P)
    #print(Ms)
    ret=None
    for perm in itertools.permutations(range(7)):
        good=True
        V={}
        for m in Ms:
            nm=''.join([str(m[perm[i]]) for i in range(7)])
            if not(nm in masks):
                good=False
                break
            else:
                V[nm]=masks[nm]
        if good:
            v=''
            for s in P[1]:
                m=tomask(s)
                nm=''.join([str(m[perm[i]]) for i in range(7)])
                v+=str(V[nm])
            cnt+=int(v)
            #print(v)
            break
print(cnt)

{'1110111': 0, '0010010': 1, '1011101': 2, '1011011': 3, '0111010': 4, '1101011': 5, '1101111': 6, '1010010': 7, '1111111': 8, '1111011': 9}
986034


In [104]:
#9a
fin=open('in.txt','r')
A=list(map(lambda s:list(map(int,list(s))),fin.read().split('\n')))
dr,dc=[1,0,-1,0],[0,1,0,-1]
s=0
for r in range(len(A)):
    for c in range(len(A[r])):
        good=True
        for d in range(4):
            nr,nc=r+dr[d],c+dc[d]
            if 0<=nr and nr<len(A) and 0<=nc and nc<len(A[r]) and A[r][c]>=A[nr][nc]:
                good=False
                break
        if good:
            s+=A[r][c]+1
s

491

In [109]:
#9b
fin=open('in.txt','r')
A=list(map(lambda s:list(map(int,list(s))),fin.read().split('\n')))
R,C=len(A),len(A[0])
dr,dc=[1,0,-1,0],[0,1,0,-1]
s=0
dest=[[None]*C for r in range(R)]
for r in range(len(A)):
    for c in range(len(A[r])):
        if A[r][c]!=9:
            bpt,bscr=None,A[r][c]
            for d in range(4):
                nr,nc=r+dr[d],c+dc[d]
                if 0<=nr and nr<len(A) and 0<=nc and nc<len(A[r]) and A[nr][nc]<bscr:
                    bpt,bscr=(nr,nc),A[nr][nc]
            dest[r][c]=bpt
par=[i for i in range(R*C)]
szs=[1]*(R*C)
def find(i):
    if i==par[i]:
        return i
    else:
        par[i]=find(par[i])
        return par[i]
def merge(i,j):
    fi,fj=find(i),find(j)
    par[fi]=fj
    szs[fj]+=szs[fi]
    szs[fi]=0
for r in range(R):
    for c in range(C):
        if A[r][c]!=9:
            i=r*C+c
            p=dest[r][c]
            if p!=None:
                merge(i,p[0]*C+p[1])
S=sorted(szs)
p=1
for v in S[-3:]:
    p*=v
p

1075536

In [112]:
#10a
fin=open('in.txt','r')
L=fin.read().split('\n')
Ps='() [] {} <>'.split(' ')
CofO={s[0]:s[1] for s in Ps}
OofC={s[1]:s[0] for s in Ps}
print(CofO,OofC)
PTs={')':3,']':57,'}':1197,'>':25137}
scr=0
for l in L:
    st=[]
    bad=None
    for c in l:
        if c in CofO:
            st.append(c)
        else:
            o=OofC[c]
            if len(st)==0 or st[-1]!=o:
                bad=c
                break
            else:
                del st[-1]
    if bad!=None:
        scr+=PTs[bad]
scr

{'(': ')', '[': ']', '{': '}', '<': '>'} {')': '(', ']': '[', '}': '{', '>': '<'}


299793

In [123]:
#10b
fin=open('in.txt','r')
L=fin.read().split('\n')
Ps='() [] {} <>'.split(' ')
CofO={s[0]:s[1] for s in Ps}
OofC={s[1]:s[0] for s in Ps}
print(CofO,OofC)
PTs={')':1,']':2,'}':3,'>':4}
scrs=[]
for l in L:
    st=[]
    bad=None
    for c in l:
        if c in CofO:
            st.append(c)
        else:
            o=OofC[c]
            if len(st)==0 or st[-1]!=o:
                bad=c
                break
            else:
                del st[-1]
    if bad==None:
        N=len(st)
        n=0
        for i in range(N):
            n*=5
            n+=PTs[CofO[st[-1]]]
            del st[-1]
        scrs.append(n)
sorted(scrs)[len(scrs)//2]

{'(': ')', '[': ']', '{': '}', '<': '>'} {')': '(', ']': '[', '}': '{', '>': '<'}


3654963618

In [138]:
#11a
fin=open('in.txt','r')
M=list(map(lambda s:list(map(int,list(s))),fin.read().split('\n')))
N=10
dr,dc=[1,1,0,-1,-1,-1,0,1],[0,1,1,1,0,-1,-1,-1]
cnt=0
for s in range(100):
#     for r in M:
#         print(''.join(map(str,r)))
#     print()
    for r in range(N):
        for c in range(N):
            M[r][c]+=1
    F=[[False]*N for r in range(N)]
    while True:
        cont=False
        for r in range(N):
            for c in range(N):
                if M[r][c]>9 and not(F[r][c]):
                    F[r][c]=True
                    cont=True
                    cnt+=1
                    for d in range(8):
                        nr,nc=r+dr[d],c+dc[d]
                        if 0<=nr and nr<N and 0<=nc and nc<N:
                            M[nr][nc]+=1
        if not(cont):
            break
    for r in range(N):
        for c in range(N):
            if F[r][c]:
                M[r][c]=0
cnt

1679

In [148]:
#11b
fin=open('in.txt','r')
M=list(map(lambda s:list(map(int,list(s))),fin.read().split('\n')))
N=10
dr,dc=[1,1,0,-1,-1,-1,0,1],[0,1,1,1,0,-1,-1,-1]
cnt=0
s=0
while True:
#     for r in M:
#         print(''.join(map(str,r)))
#     print()
    for r in range(N):
        for c in range(N):
            M[r][c]+=1
    F=[[False]*N for r in range(N)]
    while True:
        cont=False
        for r in range(N):
            for c in range(N):
                if M[r][c]>9 and not(F[r][c]):
                    F[r][c]=True
                    cont=True
                    cnt+=1
                    for d in range(8):
                        nr,nc=r+dr[d],c+dc[d]
                        if 0<=nr and nr<N and 0<=nc and nc<N:
                            M[nr][nc]+=1
        if not(cont):
            break
    tout=True
    for r in range(N):
        for c in range(N):
            if F[r][c]:
                M[r][c]=0
            else:
                tout=False
    s+=1
    if tout:
        print(s)
        break

519


In [184]:
#12a (obsolete draft)
lines=open('in.txt','r').read().split('\n')
def small(n):
    return 'a'<=n and n<='z'
edges=list(map(lambda l:tuple(l.split('-')),lines))
nodes=[]
for e in edges:
    nodes.append(e[0])
    nodes.append(e[1])
nodes=set(nodes)
graph={n:set() for n in nodes}
for e in edges:
    a,b=e
    graph[a].add(b)
    graph[b].add(a)
sadjs,eadjs=graph['start'],graph['end']
del graph['start']
del graph['end']
for n in graph:
    graph[n].discard('start')
    graph[n].discard('end')
print(graph)
#dp(u,v,l,s)=# paths u-->v w/ l edges visiting s small caves
dp={}
def calc(u,v,l,s):
    if s<0:
        return 0
    if l==0:
        return 1 if u==v and s==(1 if small(u) else 0) else 0
    code=(u,v,l,s)
    if code in dp:
        return dp[code]
    out=0
    ns=s-(1 if small(v) else 0)
    for n in graph[v]:
        out+=calc(u,n,l-1,ns)
    dp[code]=out
    return out
L=0
while True:
    nz=False
    for a in graph:
        for b in graph:
            if calc(a,b,,0)+calc(a,b,L,1)>0:
                nz=True
    if not(nz):
        break
    L+=1
s=0
for a in sadjs:
    for b in eadjs:
        for l in range(L+1):
            s+=calc(a,b,l,0)+calc(a,b,l,1)
print(dp)
print(s)

{'c': {'A'}, 'A': {'b', 'c'}, 'd': {'b'}, 'b': {'d', 'A'}}
{('c', 'c', 1, 0): 0, ('c', 'c', 1, 1): 0, ('c', 'A', 1, 0): 0, ('c', 'A', 1, 1): 1, ('c', 'd', 1, 0): 0, ('c', 'd', 1, 1): 0, ('c', 'b', 1, 0): 0, ('c', 'b', 1, 1): 0, ('A', 'c', 1, 0): 0, ('A', 'c', 1, 1): 1, ('A', 'A', 1, 0): 0, ('A', 'A', 1, 1): 0, ('A', 'd', 1, 0): 0, ('A', 'd', 1, 1): 0, ('A', 'b', 1, 0): 0, ('A', 'b', 1, 1): 1, ('d', 'c', 1, 0): 0, ('d', 'c', 1, 1): 0, ('d', 'A', 1, 0): 0, ('d', 'A', 1, 1): 0, ('d', 'd', 1, 0): 0, ('d', 'd', 1, 1): 0, ('d', 'b', 1, 0): 0, ('d', 'b', 1, 1): 0, ('b', 'c', 1, 0): 0, ('b', 'c', 1, 1): 0, ('b', 'A', 1, 0): 0, ('b', 'A', 1, 1): 1, ('b', 'd', 1, 0): 0, ('b', 'd', 1, 1): 0, ('b', 'b', 1, 0): 0, ('b', 'b', 1, 1): 0, ('c', 'c', 2, 0): 0, ('c', 'c', 2, 1): 0, ('c', 'A', 2, 0): 0, ('c', 'A', 2, 1): 0, ('c', 'd', 2, 0): 0, ('c', 'd', 2, 1): 0, ('c', 'b', 2, 0): 0, ('c', 'b', 2, 1): 0, ('A', 'c', 2, 0): 0, ('A', 'c', 2, 1): 0, ('A', 'A', 2, 0): 0, ('A', 'A', 2, 1): 2, ('A', 'd', 2, 0)

In [195]:
#12a
lines=open('in.txt','r').read().split('\n')
def small(n):
    return n=='start' or n=='end' or ('a'<=n and n<='z')
edges=list(map(lambda l:tuple(l.split('-')),lines))
nodes=[]
for e in edges:
    nodes.append(e[0])
    nodes.append(e[1])
nodes=set(nodes)
graph={n:set() for n in nodes}
for e in edges:
    a,b=e
    graph[a].add(b)
    graph[b].add(a)
print(graph)
N=len(graph)
#dp(u,v,l,m)=# paths u-->v w/ l edges visiting ea small cave at most once,
#  m=tuple of visited verts
dp={}
def calc(u,v,l,m):
    if l==0:
        return 1 if u==v and small(u)!=(u in m) else 0
    code=(u,v,l,m)
    if code in dp:
        return dp[code]
    out=0
    if not(v in m and small(v)):
        nm=m+(v,)
        for n in graph[v]:
            out+=calc(u,n,l-1,nm)
    dp[code]=out
    return out
s=0
for L in range(N+1):
    s+=calc('start','end',L,tuple())
#print(dp)
print(s)

{'ko': {'start', 'vn', 'qm', 'MV', 'DD'}, 'kw': {'lj', 'end', 'qm'}, 'start': {'MV', 'ko', 'vn'}, 'lj': {'kw', 'kh', 'KG', 'MV', 'VH'}, 'vn': {'MV', 'ko', 'start', 'DD'}, 'qm': {'ko', 'kw', 'xy', 'MV', 'DD'}, 'VH': {'lj'}, 'xy': {'MV', 'end', 'qm', 'DD'}, 'kh': {'lj'}, 'KG': {'lj', 'end'}, 'end': {'KG', 'kw', 'xy'}, 'MV': {'ko', 'start', 'lj', 'vn', 'qm', 'xy'}, 'DD': {'ko', 'vn', 'qm', 'xy'}}
3292


In [264]:
#12b
lines=open('in.txt','r').read().split('\n')
def small(n):
    return n=='start' or n=='end' or ('a'<=n and n<='z')
edges=list(map(lambda l:tuple(l.split('-')),lines))
nodes=[]
for e in edges:
    nodes.append(e[0])
    nodes.append(e[1])
nodes=set(nodes)
N=len(nodes)
idxs={}
for n in nodes:
    idxs[n]=len(idxs)
print(idxs)
graph=[[] for v in range(N)]
for e in edges:
    a,b=tuple(map(lambda v:idxs[v],e))
    graph[a].append(b)
    graph[b].append(a)
print(graph)
S,E=idxs['start'],idxs['end']
print('S,E='+str(S)+','+str(E))
cnt,cnt0=0,0
for sn in [None]+list(nodes):
    if sn==None or (sn!='start' and sn!='end' and small(sn)):
        LIM=[None for i in range(N)]
        for n in nodes:
            LIM[idxs[n]]=1 if small(n) else float('inf')
        if sn!=None:
            LIM[idxs[sn]]+=1
        print(LIM)
        dp={}
        def calc(u,v,l,f):
            if l==0:
                return 1 if (u==v and 1+f[u]<=LIM[u]) else 0
            code=(u,v,l,f)
            if code in dp:
                return dp[code]
            out=0
            if 1+f[v]<=LIM[v]:
                nf=list(f)
                nf[v]+=1
                nf=tuple(nf)
                for n in graph[v]:
                    out+=calc(u,n,l-1,nf)
            dp[code]=out
            return out
        print('sn='+str(sn))
#         if sn=='b':
#             tmp=calc(1,3,2,(0,0,0,0,1,1))
#             print(tmp)
#             print(dp)
#             print()
        s=0
        for L in range(2*N+1):
            c=calc(S,E,L,(0,)*N)
            #print(str(L)+':'+str(c))
            s+=c
#         if sn=='b':
#             print(dp)
        if sn==None:
            cnt0=s
        else:
            s-=cnt0
        print(s)
        cnt+=s
cnt

{'ko': 0, 'kw': 1, 'start': 2, 'lj': 3, 'vn': 4, 'qm': 5, 'VH': 6, 'xy': 7, 'kh': 8, 'KG': 9, 'end': 10, 'MV': 11, 'DD': 12}
[[4, 11, 5, 2, 12], [10, 5, 3], [4, 0, 11], [9, 8, 11, 1, 6], [12, 2, 11, 0], [12, 7, 1, 11, 0], [3], [11, 10, 5, 12], [3], [10, 3], [7, 9, 1], [7, 4, 3, 0, 5, 2], [4, 5, 7, 0]]
S,E=2,10
[1, 1, 1, 1, 1, 1, inf, 1, 1, inf, 1, inf, inf]
sn=None
3292
[2, 1, 1, 1, 1, 1, inf, 1, 1, inf, 1, inf, inf]
sn=ko
17280
[1, 2, 1, 1, 1, 1, inf, 1, 1, inf, 1, inf, inf]
sn=kw
302
[1, 1, 1, 2, 1, 1, inf, 1, 1, inf, 1, inf, inf]
sn=lj
16999
[1, 1, 1, 1, 2, 1, inf, 1, 1, inf, 1, inf, inf]
sn=vn
14624
[1, 1, 1, 1, 1, 2, inf, 1, 1, inf, 1, inf, inf]
sn=qm
21274
[1, 1, 1, 1, 1, 1, inf, 2, 1, inf, 1, inf, inf]
sn=xy
15821
[1, 1, 1, 1, 1, 1, inf, 1, 2, inf, 1, inf, inf]
sn=kh
0


89592

In [282]:
#13a* (imperfect recostruction because undo history was partially lost)
lines=open('in.txt','r').read().split('\n')
pts=[]
for l in lines:
    s=l.split(',')
    if len(s)==2:
        pts.append(tuple(map(int,s)))
folds=[l[len('fold along '):] for l in lines if len(l)>0 and len(l.split(','))==1]
for f in folds[:1]:
    axis,coord=f.split('=')
    coord=int(coord)
    npts=set()
    if axis=='x':
        for p in pts:
            npts.add((p[0] if p[0]<coord else 2*coord-p[0],p[1]))
    else:
        for p in pts:
            npts.add((p[0],p[1] if p[1]<coord else 2*coord-p[1]))
    pts=list(npts)
print(len(pts))

602


In [280]:
#13b
lines=open('in.txt','r').read().split('\n')
pts=[]
for l in lines:
    s=l.split(',')
    if len(s)==2:
        pts.append(tuple(map(int,s)))
folds=[l[len('fold along '):] for l in lines if len(l)>0 and len(l.split(','))==1]
for f in folds:
    axis,coord=f.split('=')
    coord=int(coord)
    npts=set()
    if axis=='x':
        for p in pts:
            npts.add((p[0] if p[0]<coord else 2*coord-p[0],p[1]))
    else:
        for p in pts:
            npts.add((p[0],p[1] if p[1]<coord else 2*coord-p[1]))
    pts=list(npts)
R,C=max([p[0] for p in pts])+1,max([p[1] for p in pts])+1
A=[[0]*R for r in range(C)]
for p in pts:
    A[p[1]][p[0]]=1
for r in A:
    for c in r:
        print('*' if c==1 else ' ',end='')
    print()

 **   **  ****   ** *  * ****  **  *  *
*  * *  * *       * *  *    * *  * * * 
*    *  * ***     * ****   *  *    **  
*    **** *       * *  *  *   *    * * 
*  * *  * *    *  * *  * *    *  * * * 
 **  *  * *     **  *  * ****  **  *  *


In [310]:
#14a
lines=open('in.txt','r').read().split('\n')
S0=lines[0]
rules={}
for l in lines[2:]:
    a,b=l.split(' -> ')
    rules[a]=b
S=S0
for rep in range(1):
    ist=[None]*(len(S)-1)
    for i in range(len(S)-1):
        p=S[i:i+2]
        if p in rules:
            ist[i]=rules[p]
    nS=[]
    for i in range(len(S)-1):
        nS.append(S[i])
        if ist[i]!=None:
            nS.append(ist[i])
    nS.append(S[-1])
    S=''.join(nS)
    #print(str(rep+1)+':'+str(len(S)))
F={}
for c in S:
    F[c]=(F[c] if c in F else 0)+1
P=sorted([(F[a],a) for a in F])
print(P)
P[-1][0]-P[0][0]

[(1, 'H'), (2, 'B'), (2, 'C'), (2, 'N')]


1

In [317]:
#14b
def add(F,k,v):
    F[k]=(F[k] if k in F else 0)+v
lines=open('in.txt','r').read().split('\n')
S0=lines[0]
L,R=S0[0],S0[-1]
SF={}
for i in range(len(S0)-1):
    p=S0[i:i+2]
    add(SF,p,1)
print(SF)
rules={}
for l in lines[2:]:
    a,b=l.split(' -> ')
    rules[a]=b
for rep in range(40):
    nSF=dict(SF)
    for p in SF:
        f=SF[p]
        if p in rules:
            v=rules[p]
            l,r=p[0]+v,v+p[1]
            add(nSF,l,f)
            add(nSF,r,f)
            add(nSF,p,-f)
    SF=nSF
F={}
for p in SF:
    add(F,p[0],SF[p])
    add(F,p[1],SF[p])
add(F,L,1)
add(F,R,1)
for p in F:
    F[p]//=2
P=sorted([(F[a],a) for a in F])
print(P)
P[-1][0]-P[0][0]

{'CF': 1, 'FF': 1, 'FP': 1, 'PO': 1, 'OH': 1, 'HB': 1, 'BC': 1, 'CV': 1, 'VV': 1, 'VN': 2, 'NP': 1, 'PH': 1, 'HC': 1, 'CN': 1, 'NB': 1, 'BK': 1, 'KV': 1, 'NV': 1}
[(596044320250, 'V'), (721076812001, 'C'), (1394050790085, 'H'), (2058813349699, 'K'), (2110238569763, 'B'), (2127526166530, 'O'), (2572922913435, 'N'), (2578458607681, 'P'), (2903118851587, 'S'), (3828470546714, 'F')]


3232426226464

From this point onward, the function add() may be referenced again.

In [321]:
#15a
lines=open('in.txt','r').read().split('\n')
M=[list(map(int,list(l))) for l in lines]
R,C=len(M),len(M[0])
S=(0,0)
front=set([S])
cost={S:0}
done=set([S])
dr,dc=[1,0,-1,0],[0,1,0,-1]
while len(front)>0:
    bv,bscr=None,float('inf')
    for v in front:
        if cost[v]<bscr:
            bscr=cost[v]
            bv=v
    done.add(bv)
    front.remove(bv)
    r,c=bv
    for d in range(4):
        nr,nc=r+dr[d],c+dc[d]
        if 0<=nr and nr<R and 0<=nc and nc<C and not((nr,nc) in done):
            n=(nr,nc)
            nscr=bscr+M[nr][nc]
            if not(n in cost) or nscr<cost[n]:
                cost[n]=nscr
                front.add(n)
cost[(R-1,C-1)]

741

In [334]:
#15b
lines=open('in.txt','r').read().split('\n')
M=[list(map(int,list(l))) for l in lines]
R,C=len(M),len(M[0])
nM=[[0]*(5*C) for r in range(5*R)]
for br in range(5):
    for bc in range(5):
        for r in range(R):
            for c in range(C):
                nM[br*R+r][bc*C+c]=1+(M[r][c]-1+br+bc)%9
M=nM
R,C=len(M),len(M[0])
front=set([S])
cost={S:0}
done=set([S])
import time
st=time.time()
while len(front)>0:
    bv,bscr=None,float('inf')
    for v in front:
        if cost[v]<bscr:
            bscr=cost[v]
            bv=v
    done.add(bv)
    front.remove(bv)
    r,c=bv
    for d in range(4):
        nr,nc=r+dr[d],c+dc[d]
        if 0<=nr and nr<R and 0<=nc and nc<C and not((nr,nc) in done):
            n=(nr,nc)
            nscr=bscr+M[nr][nc]
            if not(n in cost) or nscr<cost[n]:
                cost[n]=nscr
                front.add(n)
print(cost[(R-1,C-1)])
print(time.time()-st)

2976
27.890228986740112


In [379]:
#16a**
def bint(b):
    return int(b,base=2)
lines=open('in.txt','r').read()
bits=''.join(map(lambda c:bin(int(c,base=16))[2:].zfill(4),lines))
i=0
tver=0
while i<len(bits):
    ver,pid=bint(bits[i:i+3]),bint(bits[i+3:i+6])
    tver+=ver
    #print('i='+str(i))
    print('tver='+str(tver))
    #print(ver,pid)
    i+=6
    if pid==4:
        j=0
        lit=''
        while True:
            chunk=bits[i+j:i+j+5]
            lit+=chunk[1:]
            j+=5
            if chunk[0]=='0':
                i+=j
                #i=4*((i+3)//4)
                break
        #print(bint(lit))
    else:
        lid=bits[i]
        #print('lid='+lid)
        i+=1
        if lid=='0':
            N=15
            splen=bint(bits[i:i+15])
            i+=15
        else:
            i+=11
print(i)

tver=1
tver=5
tver=12
tver=12
tver=16
tver=16
tver=21
tver=24
tver=26
tver=26
tver=32
tver=38
tver=38
tver=42
tver=44
tver=51
tver=56
tver=59
tver=66
tver=67
tver=73
tver=76
tver=77
tver=84
tver=88
tver=94
tver=96
tver=100
tver=103
tver=106
tver=107
tver=111
tver=117
tver=120
tver=120
tver=121
tver=125
tver=131
tver=138
tver=142
tver=147
tver=148
tver=151
tver=157
tver=157
tver=158
tver=163
tver=168
tver=171
tver=172
tver=172
tver=172
tver=174
tver=174
tver=175
tver=178
tver=184
tver=187
tver=187
tver=194
tver=201
tver=206
tver=206
tver=213
tver=215
tver=221
tver=223
tver=225
tver=228
tver=228
tver=229
tver=229
tver=230
tver=232
tver=235
tver=235
tver=238
tver=240
tver=246
tver=250
tver=257
tver=263
tver=267
tver=273
tver=280
tver=287
tver=291
tver=297
tver=297
tver=298
tver=302
tver=305
tver=306
tver=308
tver=315
tver=317
tver=320
tver=321
tver=324
tver=327
tver=327
tver=328
tver=328
tver=329
tver=336
tver=340
tver=347
tver=347
tver=353
tver=353
tver=357
tver=358
tver=360
tver=361
tve

ValueError: invalid literal for int() with base 2: ''

In [378]:
#16b**
def bint(b):
    return int(b,base=2)
lines=open('in.txt','r').read()
bits=''.join(map(lambda c:bin(int(c,base=16))[2:].zfill(4),lines))
def calc(i):
    ver,pid=bint(bits[i:i+3]),bint(bits[i+3:i+6])
    #print('i='+str(i))
    #print(ver,pid)
    i+=6
    if pid==4:
        j=0
        lit=''
        while True:
            chunk=bits[i+j:i+j+5]
            lit+=chunk[1:]
            j+=5
            if chunk[0]=='0':
                i+=j
                break
        return bint(lit),i
    else:
        lid=bits[i]
        #print('lid='+lid)
        i+=1
        vals=[]
        if lid=='0':
            N=15
            splen=bint(bits[i:i+N])
            i+=N
            rem=splen
            while rem>0:
                v,ni=calc(i)
                vals.append(v)
                rem-=ni-i
                i=ni
        else:
            N=11
            spcnt=bint(bits[i:i+N])
            i+=N
            for rep in range(spcnt):
                v,ni=calc(i)
                vals.append(v)
                i=ni
        if pid in set([0,1,2,3]):
            def prod(L):
                out=1
                for v in L:
                    out*=v
                return out
            return (sum,prod,min,max)[pid](vals),i
        elif pid==5:
            return 1 if vals[0]>vals[1] else 0,i
        elif pid==6:
            return 1 if vals[0]<vals[1] else 0,i
        else:
            return 1 if vals[0]==vals[1] else 0,i
calc(0)

(5390807940351, 5478)

In [ ]:
#17a (!!!does not terminate)
lines=open('in.txt','r').read().split(' ')[2:]
XS=tuple(map(int,lines[0][2:-1].split('..')))
YS=tuple(map(int,lines[1][2:].split('..')))
maxy=-float('inf')
vy0=YS[0]-1
while True:
    for vx0 in range(0,XS[1]+1):
        #simulate
        x,y=0,0
        vx,vy=vx0,vy0
        good=False
        peaky=-float('inf')
        while True:
            x+=vx
            y+=vy
            peaky=max(peaky,y)
            if vx>0:
                vx-=1
            elif vx<0:
                vx+=1
            vy-=1
            if x>XS[1] or y<YS[0]:
                break
            if XS[0]<=x and x<=XS[1] and YS[0]<=y and y<=YS[1]:
                good=True
                break
        if good:
            maxy=max(maxy,peaky)
            print(maxy)
    vy0+=1
maxy

In [ ]:
#17b (!!!does not terminate)
lines=open('in.txt','r').read().split(' ')[2:]
XS=tuple(map(int,lines[0][2:-1].split('..')))
YS=tuple(map(int,lines[1][2:].split('..')))
cnt=0
vy0=YS[0]-1
while True:
    for vx0 in range(0,XS[1]+1):
        #simulate
        x,y=0,0
        vx,vy=vx0,vy0
        good=False
        peaky=-float('inf')
        while True:
            x+=vx
            y+=vy
            peaky=max(peaky,y)
            if vx>0:
                vx-=1
            elif vx<0:
                vx+=1
            vy-=1
            if x>XS[1] or y<YS[0]:
                break
            if XS[0]<=x and x<=XS[1] and YS[0]<=y and y<=YS[1]:
                good=True
                break
        if good:
            cnt+=1
            print(cnt)
    vy0+=1
maxy

In [513]:
#18a,b
lines=open('in.txt','r').read().split('\n')
class Node:
    def __init__(self,v,p,cs):
        self.val=v
        self.parent=p
        self.children=cs
    def add_child(self,c):
        self.children.append(c)
        c.parent=self
    def __str__(self):
        return '['+(','.join(map(str,self.children)))+']' if self.val==None else str(self.val)
    def isnum(self):
        return self.val!=None
def tree(s):
    stack=[]
    root=None
    i=0
    while i<len(s):
        #print(list(map(str,stack)))
        if s[i]=='[':
            n=Node(None,None,[])
            if root==None:
                root=n
            if len(stack)>0:
                p=stack[-1]
                p.add_child(n)
            stack.append(n)
            i+=1
        elif s[i]==']':
            stack.pop()
            i+=1
        elif s[i]==',':
            i+=1
        else:
            j=i
            while '0'<=s[j] and s[j]<='9':
                j+=1
            n=Node(int(s[i:j]),None,[])
            p=stack[-1]
            p.add_child(n)
            i=j
    return root
def printtree(n,d=0):
    print(''*d+str(n.val))
    for c in n.children:
        printtree(c,d+1)
def add(T,U):
    n=Node(None,None,[])
    n.add_child(T)
    n.add_child(U)
    return n
def explode(T):
    STOP=[False]
    def dfs(n,d):
        #print(str(n))
        if STOP[0]:
            return
        if not(n.isnum()):
            l,r=n.children
            if (l.isnum()
                and r.isnum()
                and d>=4):
                #can a pair of pairs explode? (apparently no)
                a,b=l.val,r.val
                #add to left
                anc,pd=n,d
                while pd>0:
                    p=anc.parent
                    if p.children[0]!=anc:
                        nn=p.children[0]
                        while not(nn.isnum()):
                            nn=nn.children[1]
                        nn.val+=a
                        break
                    anc,pd=p,pd-1
                #add to right
                anc,pd=n,d
                while pd>0:
                    p=anc.parent
                    if p.children[1]!=anc:
                        nn=p.children[1]
                        while not(nn.isnum()):
                            nn=nn.children[0]
                        nn.val+=b
                        break
                    anc,pd=p,pd-1
                #replace node
                p=n.parent
                p.children[p.children.index(n)]=Node(0,p,[])
                STOP[0]=True
                return
        for c in n.children:
            dfs(c,d+1)
    dfs(T,0)
    return STOP[0]
def split(T):
    STOP=[False]
    def dfs(n,d):
        #print(str(n))
        if STOP[0]:
            return
        if n.isnum() and n.val>=10:
            v=n.val
            l,r=Node(v//2,None,[]),Node((v+1)//2,None,[])
            n.add_child(l)
            n.add_child(r)
            n.val=None
            STOP[0]=True
            return
        for c in n.children:
            dfs(c,d+1)
    dfs(T,0)
    return STOP[0]
def reduce(T):
    while explode(T) or split(T):
        pass
def mag(T):
    return (T.val if T.isnum()
            else 3*mag(T.children[0])+2*mag(T.children[1]))
T=tree(lines[0])
for l in lines[1:]:
    T=add(T,tree(l))
    reduce(T)
print(mag(T))
m=0
for a in lines:
    for b in lines:
        T=add(tree(a),tree(b))
        reduce(T)
        m=max(m,mag(T))
print(m)

3816
4819


In [500]:
#obsolete draft for 18a
def nums(s):
    out=[]
    lvl=0
    i=0
    while i<len(s):
        #print(list(map(str,stack)))
        if s[i]=='[':
            lvl+=1
            i+=1
        elif s[i]==']':
            lvl-=1
            i+=1
        elif s[i]==',':
            i+=1
        else:
            j=i
            while '0'<=s[j] and s[j]<='9':
                j+=1
            out.append([int(s[i:j]),lvl])
            i=j
    return out
def add(T,U):
    return list(map(lambda n:[n[0],n[1]+1],T+U))
def explode(T):
    for i in range(len(T)-1):
        d=T[i][1]
        if d==T[i+1][1] and d>=5:
            a,b=T[i][0],T[i+1][0]
            if i>0:
                T[i-1][0]+=a
            if i<len(T)-2:
                T[i+2][0]+=b
            T[i]=[0,d-1]
            del T[i+1]
            return True
    return False
def split(T):
    for i in range(len(T)):
        v,d=T[i]
        if v>=10:
            T[i]=[v//2,d+1]
            T.insert(i+1,[(v+1)//2,d+1])
            return True
    return False
def reduce(T):
    while explode(T):
        pass
    while split(T):
        pass
T=nums('[[[[[4,3],4],4],[7,[[8,4],9]]],[1,1]]')
print(T)
reduce(T)
print(T)

[[4, 5], [3, 5], [4, 4], [4, 3], [7, 3], [8, 5], [4, 5], [9, 4], [1, 2], [1, 2]]
[[0, 4], [7, 4], [4, 3], [7, 4], [8, 4], [0, 4], [6, 5], [7, 5], [1, 2], [1, 2]]


In [554]:
import numpy as np

In [579]:
XY=np.array([[0,-1,0],[1,0,0],[0,0,1]])
YZ=np.array([[1,0,0],[0,0,-1],[0,1,0]])
ZX=np.array([[0,0,1],[0,1,0],[-1,0,0]])
def matpow(M,p):
    r=np.eye(len(M),dtype=int)
    for rep in range(p):
        r=r@M
    return r
ROTS=set()
for a in range(4):
    for b in range(4):
        for c in range(4):
            ROTS.add(tuple(
                (matpow(ZX,c)@matpow(YZ,b)@matpow(XY,a))
            .flatten()))
ROTS=[np.array(t).reshape((3,3)) for t in ROTS]
print(len(ROTS))
ROTS

24


[array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1]]),
 array([[ 0,  1,  0],
        [-1,  0,  0],
        [ 0,  0,  1]]),
 array([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]]),
 array([[ 0,  1,  0],
        [ 1,  0,  0],
        [ 0,  0, -1]]),
 array([[ 0, -1,  0],
        [ 1,  0,  0],
        [ 0,  0,  1]]),
 array([[ 1,  0,  0],
        [ 0,  0,  1],
        [ 0, -1,  0]]),
 array([[ 0, -1,  0],
        [-1,  0,  0],
        [ 0,  0, -1]]),
 array([[ 0,  1,  0],
        [ 0,  0, -1],
        [-1,  0,  0]]),
 array([[ 0, -1,  0],
        [ 0,  0, -1],
        [ 1,  0,  0]]),
 array([[ 0,  0, -1],
        [ 0, -1,  0],
        [-1,  0,  0]]),
 array([[ 0,  0,  1],
        [-1,  0,  0],
        [ 0, -1,  0]]),
 array([[ 0, -1,  0],
        [ 0,  0,  1],
        [-1,  0,  0]]),
 array([[ 0,  0, -1],
        [-1,  0,  0],
        [ 0,  1,  0]]),
 array([[ 0,  0,  1],
        [ 0, -1,  0],
        [ 1,  0,  0]]),
 array([[ 0,  0,  1],
        [ 0,  1,  0],
        [-1, 

In [598]:
#19a (very slow)
lines=open('in.txt','r').read().split('\n')
scid=-1
ptss=[]
for l in lines:
    if l[:3]=='---':
        scid=int(l[len('--- scanner '):-4])
        #print(scid)
        ptss.append(set())
    elif len(l)>0:
        ptss[-1].add(tuple(map(int,l.split(','))))
def transform(A,rot,tl):
    out=set()
    for p in A:
        out.add(tuple((ROTS[rot]@(np.array(p).reshape((3,1)))).flatten()+tl))
    return out
def matches(A,B):
    out=set()
    for p in A:
        if p in B:
            out.add(p)
    return out
def overlap(A,B):
    #returns overlapping points, relative to B
    for p in A:
        for b in B:
            for rot in range(24):
                tmp=transform(set([p]),rot,[0]*3)
                tp=None
                for t in tmp:
                    tp=t
                tl=[b[i]-tp[i] for i in range(3)]
                tA=transform(A,rot,tl)
                ms=matches(tA,B)
                if len(ms)>=12:
                    return ms,(rot,tl)
    return None
cnt=len(ptss)
while cnt>1:
    cnt0=cnt
    for i in range(1,len(ptss)):
        if ptss[i]!=None:
            print('check '+str(i))
            ret=overlap(ptss[i],ptss[0])
            if ret!=None:
                print('merge 0,{}'.format(i))
                #print(ret[0])
                ts=transform(ptss[i],*ret[1])
                for pt in ts:
                    ptss[0].add(pt)
                ptss[i]=None
                cnt-=1
    if cnt0==cnt:
        break
print(cnt)
len(ptss[0])

check 1
check 2
check 3
check 4
check 5
check 6
check 7
check 8
check 9
check 10
check 11
check 12
check 13
check 14
check 15
check 16
check 17
check 18
check 19
check 20
check 21
check 22
check 23
check 24
check 25
check 26
check 27
check 28
check 29
check 30
check 31
merge 0,31
check 32
check 33
check 34
check 35
check 36
check 37
check 1
check 2
check 3
check 4
check 5
check 6
check 7
check 8
check 9
check 10
check 11
check 12
check 13
check 14
merge 0,14
check 15
check 16
check 17
check 18
check 19
check 20
merge 0,20
check 21
check 22
check 23
check 24
check 25
check 26
check 27
check 28
check 29
check 30
merge 0,30
check 32
merge 0,32
check 33
check 34
check 35
check 36
check 37
merge 0,37
check 1
merge 0,1
check 2
check 3
check 4
check 5
check 6
check 7
check 8
check 9
check 10
check 11
merge 0,11
check 12
check 13
merge 0,13
check 15
check 16
check 17
merge 0,17
check 18
check 19
check 21
check 22
check 23
merge 0,23
check 24
merge 0,24
check 25
check 26
merge 0,26
check 27
che

454

In [620]:
#19b (but also includes part 19a)
lines=open('in.txt','r').read().split('\n')
scid=-1
ptss=[]
for l in lines:
    if l[:3]=='---':
        scid=int(l[len('--- scanner '):-4])
        #print(scid)
        ptss.append(set())
    elif len(l)>0:
        ptss[-1].add(tuple(map(int,l.split(','))))
def transform(A,rot,tl):
    out=set()
    for p in A:
        out.add(tuple((ROTS[rot]@(np.array(p).reshape((3,1)))).flatten()+tl))
    return out
def matches(A,B):
    out=set()
    for p in A:
        if p in B:
            out.add(p)
    return out
def overlap(A,B):
    #returns overlapping points, relative to B
    #much faster than previous version of overlap() function
    for rot in range(24):
        tA=transform(A,rot,[0]*3)
        shifts={}
        for p in tA:
            for b in B:
                s=tuple([b[i]-p[i] for i in range(3)])
                shifts[s]=(shifts[s] if s in shifts else 0)+1
        ms=sorted([(shifts[s],s) for s in shifts],reverse=True)[0]
        if ms[0]>=12:
            tl=ms[1]
            return matches(transform(A,rot,tl),B),(rot,tl)
    return None
cnt=len(ptss)
scanners=[(0,)*3]
while cnt>1:
    cnt0=cnt
    for i in range(1,len(ptss)):
        if ptss[i]!=None:
            #print('check '+str(i))
            ret=overlap(ptss[i],ptss[0])
            if ret!=None:
                loc=ret[1][1]
                scanners.append(loc)
                print(str(i)+' @ '+str(loc))
                ts=transform(ptss[i],*ret[1])
                for pt in ts:
                    ptss[0].add(pt)
                ptss[i]=None
                cnt-=1
    if cnt0==cnt:
        break
print(len(ptss[0])) #part a
md=0
for a in scanners:
    for b in scanners:
        md=max(md,sum(abs(a[i]-b[i]) for i in range(3)))
print(md)

31 @ (4, 47, -1267)
14 @ (-1258, 49, -1267)
20 @ (1074, 32, -1341)
30 @ (2258, 18, -1189)
32 @ (1027, -1288, -1269)
37 @ (1201, -1241, 8)
1 @ (1089, -2498, -141)
11 @ (1110, 51, -2440)
13 @ (3450, 70, -1337)
17 @ (2398, -33, -2485)
23 @ (2306, -92, -3602)
24 @ (-16, -2343, -81)
26 @ (3450, -1269, -1281)
34 @ (2379, -1273, -3685)
35 @ (3466, 1266, -1242)
36 @ (4639, -28, -1265)
2 @ (3535, 58, -2506)
3 @ (2348, -1129, -4890)
5 @ (2277, 1100, -3708)
8 @ (4808, -1260, -1223)
9 @ (3601, -2448, -1175)
10 @ (2414, -2378, -4758)
12 @ (3614, -37, -3709)
15 @ (5892, -6, -1222)
16 @ (2233, -2346, -3656)
18 @ (5965, 49, -2516)
19 @ (3614, -1233, -84)
21 @ (2416, -1143, -5988)
22 @ (1045, -1158, -3701)
25 @ (2295, -2518, -1152)
27 @ (3591, -1195, -3613)
28 @ (1152, -2397, -4904)
29 @ (3521, 45, -4834)
33 @ (2359, -2524, -2370)
4 @ (2284, -3607, -1157)
6 @ (1064, -2455, -3581)
7 @ (4650, -71, -3704)
454
10813


In [647]:
int('011',2)

3

In [ ]:
#20a
lines=open('in.txt','r').read().split('\n')
def tobin(s):
    return [1 if c=='#' else 0 for c in s]
def pboard(A):
    for r in A:
        for c in r:
            print('#' if c==1 else '.',end='')
        print('')
    print('')
alg=tobin(lines[0])
#print(alg)
mat=list(map(tobin,lines[2:]))
R,C=len(mat),len(mat[0])
#print(R,C)
#expand
S=8
tmp=[[0]*(C+2*S) for r in range(R+2*S)]
for r in range(R):
    for c in range(C):
        tmp[r+S][c+S]=mat[r][c]
M,N=len(tmp),len(tmp[0])
pboard(tmp)
for rep in range(2):
    nm=[[0]*N for r in range(M)]
    for r in range(1,M-1):
        for c in range(1,N-1):
            nums=[]
            for tr in range(-1,2):
                for tc in range(-1,2):
                    nums.append(tmp[r+tr][c+tc])
            n=int(''.join(map(str,nums)),2)
            #print(r,c,nums,n)
            nm[r][c]=alg[n]
    tmp=nm
    pboard(tmp)
ret=np.array(tmp)[S-4:S+R+4,S-4:S+C+4]
pboard(ret)
sum(map(sum,ret))

In [668]:
#20b
lines=open('in.txt','r').read().split('\n')
def tobin(s):
    return [1 if c=='#' else 0 for c in s]
def pboard(A):
    for r in A:
        for c in r:
            print('#' if c==1 else '.',end='')
        print('')
    print('')
alg=tobin(lines[0])
#print(alg)
mat=list(map(tobin,lines[2:]))
R,C=len(mat),len(mat[0])
#print(R,C)
#expand
REPS=50
L=2*REPS
S=2*L+10
tmp=[[0]*(C+2*S) for r in range(R+2*S)]
for r in range(R):
    for c in range(C):
        tmp[r+S][c+S]=mat[r][c]
M,N=len(tmp),len(tmp[0])
for rep in range(1,REPS+1):
    nm=[[0]*N for r in range(M)]
    for r in range(1,M-1):
        for c in range(1,N-1):
            nums=[]
            for tr in range(-1,2):
                for tc in range(-1,2):
                    nums.append(tmp[r+tr][c+tc])
            n=int(''.join(map(str,nums)),2)
            #print(r,c,nums,n)
            nm[r][c]=alg[n]
    tmp=nm
    print(rep,sum(map(sum,np.array(tmp)[S-2*rep:S+R+2*rep,S-2*rep:S+C+2*rep])))
    #pboard(tmp)
ret=np.array(tmp)[S-L:S+R+L,S-L:S+C+L]
#pboard(ret)
sum(map(sum,ret))

1 5786
2 5419
3 7081
4 5822
5 8749
6 6235
7 10345
8 6618
9 12160
10 6944
11 13886
12 7466
13 15857
14 7961
15 18002
16 8309
17 20138
18 8763
19 22541
20 9309
21 24944
22 9720
23 27495
24 10158
25 30182
26 10634
27 32826
28 11177
29 35853
30 11759
31 38920
32 12296
33 42083
34 12683
35 45434
36 13273
37 48826
38 13854
39 52198
40 14330
41 55939
42 14992
43 59671
44 15399
45 63572
46 16083
47 67297
48 16786
49 71512
50 17325


17325

In [ ]:
#21a
lines=open('in.txt','r').read().split('\n')